package com.github.gpaddons.gppmcaddons.listeners;

import com.github.gpaddons.gppmcaddons.utils.HorseUtils;
import me.ryanhamshire.GriefPrevention.events.ClaimPermissionCheckEvent;
import org.bukkit.block.Block;
import org.bukkit.entity.Horse;
import org.bukkit.entity.Player;
import org.bukkit.event.Event;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockPlaceEvent;


public class HorsePermissionListener implements Listener {

    @EventHandler(priority = EventPriority.HIGH, ignoreCancelled = false)
    public void onCheckPermission(ClaimPermissionCheckEvent event)
    {
        Player player = event.getCheckedPlayer();
        Event triggeringEvent = event.getTriggeringEvent();

        if (player == null) return;

        // Check if triggering event is a BlockPlaceEvent generated by GP
        if (triggeringEvent instanceof BlockPlaceEvent blockEvent)
        {
            // Check if block is a fence
            Block block = blockEvent.getBlock();
            if (!HorseUtils.isFenceBlock(block)) return;

            // Check whether a horse with which the player interacts exists
            Horse horse = HorseUtils.getHorseFromFence(block, player);
            if (horse == null) return;

            // Check if horse has an owner
            Player owner = HorseUtils.getHorseOwner(horse);
            if (owner == null) return;

            // Check if player is the owner and allow the action
            if (owner.getUniqueId().equals(player.getUniqueId()))
                event.setDenialReason(null);
        }
    }
}
