name: Auto-merge Dependabot PRs

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  auto-merge:
    if: ${{ github.actor == 'dependabot[bot]'
      && github.event.workflow_run.event == 'pull_request'
      && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 🔀 Merge Pull Request
        uses: peter-evans/merge-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request: ${{ github.event.workflow_run.pull_requests[0].number }}
          merge-method: squash