name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ☕ Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 🪶 Build with Maven
        run: mvn clean package

      - name: 📦 Auto-detect artifacts
        run: |-
          artifacts="$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.build.directory}${file.separator}${project.build.finalName}.jar' exec:exec)"
          printf "maven-artifacts<<EOF\n%s\nEOF\n" "$artifacts" >> "$GITHUB_ENV"

      - name: 📦 Upload auto-detected artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-ci
          path: ${{ env.maven-artifacts }}
